### PR TITLE
Add color plugin

### PR DESCRIPTION
**Pull request by blowmage**
Add the minitest-rg functionality, but renamed to color to match the RSpec naming. In reference to #495.

### CODE REVIEW

**Comment by blowmage** [comment]
If you run the tests with a rake task the `-c`/`--color` flags can be set by using the `TESTOPTS` environment variable.

```
$ rake test TESTOPTS="-c"
$ rake test TESTOPTS="--color"
```

**Comment by zenspider** [comment]
Shit. I totally misunderstood your offer. I simply thought a gem had been renamed and you were offering a PR to fix the readme listing for it.

**Comment by blowmage** [comment]
Hah! I kinda wondered. :)

**Comment by zenspider** [comment]
Closing. Please send me a PR and add color to the FAQ pointing to your gem.

**Pull request closed without merging**
