### PR TITLE
Add nodoc label to Unit::after_tests

### PR DESCRIPTION
**Pull request by davydovanton**
:cake:

### CODE REVIEW

**Comment by zenspider** [comment]
Good catch! Dunno why my `rake dcov` isn't reporting that!

**Comment by davydovanton** [comment]
Thanks! http://www.docsdoctor.org helped me :)

/cc @schneems

**Comment by zenspider** [comment]
how?

docsdoctor looks neat, but it 404s on minitest. :(

**Comment by schneems** [comment]
Great! The site works for me http://www.docsdoctor.org/seattlerb/minitest

**Comment by zenspider** [comment]
@schneems this is your baby, right? There's a bug in the homepage after login. If you search down for minitest, you'll see that the link is `http://www.docsdoctor.org/seattlerb%2Fminitest` and that 404s. Looks like you're double escaping somewhere?

**Comment by schneems** [comment]
Idk I spent some time looking at it but couldn't find the root cause https://github.com/codetriage/docs_doctor/issues/50#issuecomment-196359033

**Comment by davydovanton** [comment]
@zenspider hello, what about this patch? :smiley:

**Comment by zenspider** [comment]
@davydovanton relax... I was working on a talk and going to a conference.

**Comment by zenspider** [comment]
Done. Thanks!

**Comment by davydovanton** [comment]
@zenspider no problem, good luck on conference/meetup!
Thanks for merge :tada:

**Pull request closed without merging**
