### PR TITLE
Add negative filters

### PR DESCRIPTION
**Pull request by utilum**

### CODE REVIEW

**Comment by utilum** [comment]
#519

**Comment by zenspider** [comment]
OK. I need to ponder. This requires dropping compatibility. I'd like to get numbers to make an informed decision.

**Comment by utilum** [comment]
Dropping compatibility with 1.8.7 sounds harsh. What if I move the file filtering into a plugin that could be combined with tools like minitest-bisect when needed ?

**Comment by zenspider** [comment]
I'm using this right now with just `-e` and I love it. We could forego the file exclusion thing for a plugin for now?

**Comment by utilum** [comment]
Yes, that's the idea. See pull request 602.

**Pull request closed without merging**
