### PR TITLE
add assert_not_equal method (and unit test for it)

### PR DESCRIPTION
**Pull request by sebhtml**

### CODE REVIEW

**Comment by zenspider** [comment]
I can not accept this PR. Please go watch any of my minitest talks for a thorough explanation why.

**Comment by sebhtml** [comment]
Can you provide a hyper link to one of these talks ?

**Comment by sebhtml** [comment]
I see. This is neat. I have to use refute_equal.

http://www.zenspider.com/pdf/2015_railsconf_ruby_on_rails_on_minitest.pdf

Thanks for pointing this.

**Comment by zenspider** [comment]
_By itself_, `refute_equal` is a bad assertion. Only use it to contrast a difference with a previous `assert_equal`.

**Pull request closed without merging**
