### PR TITLE
Add MiniTest::Assertions#assert_not

### PR DESCRIPTION
**Pull request by bogdanvlviv**

### CODE REVIEW

**Comment by zenspider** [comment]
Thanks for the PR, but have you seen `refute`?

**Comment by bogdanvlviv** [comment]
ah, yes. thanks. i will close it

**Comment by zenspider** [comment]
Thanks tho!

**Comment by zenspider** [comment]
Curious, but I'd that was a failure in documentation, can you open an issue and point it out?

**Comment by bogdanvlviv** [comment]
@zenspider The documentation is LGTM. Could you please explain more what do you mean?

**Comment by zenspider** [comment]
Just want to know if there is some place the documentation can improve.

**Pull request closed without merging**
