### PR TITLE
[ci skip] Document how to run tests via Rake

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by utilum** [comment]
Minitest's own tests suggest  `t.test_files = FileList["test/**/test_*.rb"]`

**Comment by utilum** [comment]
Perhaps noting that options then need to be passed in `TESTOPTS` ?

**Comment by zenspider** [comment]
I'm gonna add this... and it's gonna last about 2 weeks. After that, I'm adding `minitest/test_task.rb` and replacing the doco for that. Rake::TestTask is an unusable abomination.

**Comment by zenspider** [comment]
Done. Thank you. Sorry I took so long to tend to this.

**Pull request closed without merging**
