### PR TITLE
`minitest-heat` Reporter

### PR DESCRIPTION
**Pull request by garrettdimon**
Adding [minitest-heat reporter](https://github.com/garrettdimon/minitest-heat/wiki) to the list.

### CODE REVIEW

**Comment by zenspider** [comment]
This looks awesome!

One request (for your code)... please put some sort of header/footer on it so it can be found... Our CI at work runs on ~40 jobs across hundreds of test files and I'll need to grab the logs and combine all the results to make it worthwhile.

**Comment by zenspider** [comment]
Done. Thanks!

**Comment by garrettdimon** [comment]
I think I know what you mean about the header/footer, but do you have an example from other reporters so I can make sure it's a good solution? And I assume it's something that would be fine being configurable so teams/contexts that don't need it don't have the extra visual noise?

**Comment by zenspider** [comment]
Something like that… No examples off the top of my head. honestly, even if you just do a stupid markdownish header (eg `## Heat Map`) and had a consistent format after that, I’m sure it’d be extractable enough.

I guess the question remaining is: how to extract multiple and combine them in a meaningful way?

**Pull request closed without merging**
